#!/system/bin/sh

sync
busybox mount -o rw,remount /system;

MTD=`ls -d /sys/block/mtd*`;
LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;
for j in $MMC $MTD $LOOP $RAM;
do
busybox echo "0" > $j/queue/rotational;
busybox echo "2048" > $j/queue/read_ahead_kb;. 
done;

# Set SD Card Cache
busybox echo "2048" > /sys/devices/virtual/bdi/179:0/read_ahead_kb

# etc
busybox echo "0" > /proc/sys/net/ipv6/conf/all/forwarding
busybox echo "0" > /proc/sys/net/ipv4/tcp_timestamps
busybox echo "1" > /proc/sys/net/ipv4/tcp_no_metrics_save
busybox echo "1" > /proc/sys/net/ipv4/tcp_tw_reuse;
busybox echo "1" > /proc/sys/net/ipv4/tcp_sack;
busybox echo "1" > /proc/sys/net/ipv4/tcp_tw_recycle;
busybox echo "1" > /proc/sys/net/ipv4/tcp_window_scaling;
busybox echo "5" > /proc/sys/net/ipv4/tcp_keepalive_probes;
busybox echo "30" > /proc/sys/net/ipv4/tcp_keepalive_intvl;

# Make perms all loosey-goosey
chown radio system /sys/android_power/state
chown radio system /sys/android_power/request_state
chown radio system /sys/android_power/acquire_full_wake_lock
chown radio system /sys/android_power/acquire_partial_wake_lock
chown radio system /sys/android_power/release_wake_lock
chown system system /sys/power/autosleep
chown system system /sys/power/state
chown system system /sys/power/wakeup_count
chown radio system /sys/power/wake_lock
chown radio system /sys/power/wake_unlock
chmod 0660 /sys/power/state
chmod 0660 /sys/power/wake_lock
chmod 0660 /sys/power/wake_unlock
chown system system /sys/devices/system/cpu/cpufreq/interactive/timer_rate
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/timer_rate
chown system system /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/min_sample_time
chown system system /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/hispeed_freq
chown system system /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/go_hispeed_load
chown system system /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/above_hispeed_delay
chown system system /sys/devices/system/cpu/cpufreq/interactive/boost
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/boost
chown system system /sys/devices/system/cpu/cpufreq/interactive/boostpulse
chown system system /sys/devices/system/cpu/cpufreq/interactive/input_boost
chmod 0660 /sys/devices/system/cpu/cpufreq/interactive/input_boost

# Memory Thresholds
FOREGROUND_APP_MEM=2048
VISIBLE_APP_MEM=3072
PERCEPTIBLE_APP_MEM=4096
HEAVY_WEIGHT_APP_MEM=6144
SECONDARY_SERVER_MEM=7168
BACKUP_APP_MEM=7168
HOME_APP_MEM=4096
HIDDEN_APP_MEM=10240
EMPTY_APP_MEM=12288

# Apply MEM limits
busybox echo $FOREGROUND_APP_MEM,$VISIBLE_APP_MEM,$PERCEPTIBLE_APP_MEM,$SECONDARY_SERVER_MEM,$HIDDEN_APP_MEM,$EMPTY_APP_MEM > /sys/module/lowmemorykiller/parameters/minfree

setprop ro.FOREGROUND_APP_MEM $FOREGROUND_APP_MEM
setprop ro.VISIBLE_APP_MEM $VISIBLE_APP_MEM
setprop ro.PERCEPTIBLE_APP_MEM $PERCEPTIBLE_APP_MEM
setprop ro.HEAVY_WEIGHT_APP_MEM $HEAVY_WEIGHT_APP_MEM
setprop ro.SECONDARY_SERVER_MEM $SECONDARY_SERVER_MEM
setprop ro.BACKUP_APP_MEM $BACKUP_APP_MEM
setprop ro.HOME_APP_MEM $HOME_APP_MEM
setprop ro.HIDDEN_APP_MEM $HIDDEN_APP_MEM
setprop ro.EMPTY_APP_MEM $EMPTY_APP_MEM

# drop garbage in caches
rm -f /cache/*.apk;
rm -f /cache/*.tmp;
rm -f /data/dalvik-cache/*.apk;
rm -f /data/dalvik-cache/*.tmp;
rm -f /data/system/dropbox/*;

# Enable Sysctl Tweaks
sysctl -p /system/etc/sysctl.conf

# File System Tweaks & Cleanup
busybox mount -o remount,noatime,noauto_da_alloc,nodiratime,barrier =0,nobh /system
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /data
busybox mount -o remount,noatime,noauto_da_alloc,nosuid,nodev,nodir atime,barrier=0,nobh /cache
busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nodev /sys

# Breaking the lease
busybox echo "15" > /proc/sys/fs/lease-break-time

sync
busybox mount -o ro,remount /system;
